valor = input('Digite algo: ')
print('O tipo primitivo desse valor é:', type(valor))
print('Só tem espaços?', valor.isspace())
print('É um número?', valor.isnumeric())
print('É alfabético?', valor.isalpha())
print('É alfanúmerico?', valor.isalnum())
print('É maiúsculo?', valor.isupper())
print('É minúsculo?', valor.islower())
print('Está capitalizada?', valor.istitle())
